name: Deploy to Server

on:
  push:
    branches:
      - main  # Déclenche le workflow sur un push vers la branche main

jobs:
  processus_de_deploiement:
    runs-on: ubuntu-latest
    # needs:
    #   - Test-process
    environment:
      name: production

    steps:
      - name: Pull Git Repository
        uses: actions/checkout@v2

      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo /usr/local/bin/update_frontend.sh

  # deploy:
  #   runs-on: ubuntu-latest
  #   environment: production
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Deploy to server via SSH
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.SERVER_IP }}  # IP de votre serveur
  #         username: ${{ secrets.SERVER_USERNAME }}  # Utilisateur SSH
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}  # Clé privée SSH
  #         script: |
  #           sudo /usr/local/bin/update_frontend.sh

    